### ISSUE TITLE
Game crashes when I try to add or edit a block in the config gui

### ISSUE THREAD

**Issue by zLudociel** [AdvancedXRay/XRay-Fabric#20]
**Describe the bug**
When I open the GUI with 'G' and use any of the methods to add a block my game immediately crashes. When I edit one of the existing blocks with shift and click my game crashes, I was trying to add an xray for an ender chest.

**To Reproduce**
1. Open a world
2. Open the GUI
3. Do one of these four things:
    a. Press 'add block', search for a block and click it.
    b. Hold a block in your hand, then press 'add block in hand'.
    c. Place a block, look at it, then press 'add block looking at'.
    d. hover over a previously added block and shift+click it.

**Expected behavior**
The game should not crash.

**Minecraft Enviorment**
 - Minecraft Version: [1.17.1]
 - XRay Mod Version: [advanced-xray-fabric-1.17-0.6.0-build.8]

**Additional context**
Crash log:
```
[10:14:31] [main/INFO]: Loading for game Minecraft 1.17.1
[10:14:32] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b44633d, also found 0.3.0+a02b446318
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+198a96213d, also found 1.0.4+cbda931818
[10:14:32] [main/INFO]: [FabricLoader] Loading 69 mods:
	- advanced-xray-fabric@0.6.0-build.8
	- atomic@1.0.0
	- baritone@1.7.0
	- chesttracker@1.1.1
	- cloth-api@2.0.54
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.0.38
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- club_minnced_java-discord-rpc@2.0.1
	- com_github_hube12_seed@master-SNAPSHOT
	- fabric@0.40.8+1.17
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-api-lookup-api-v1@1.3.0+cbda931818
	- fabric-biome-api-v1@3.2.0+cbda931818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+cbda931818
	- fabric-content-registries-v0@0.3.0+cbda931818
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.2.3+87cc6e4c18
	- fabric-events-interaction-v0@0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+cbda931818
	- fabric-item-api-v1@1.2.4+cbda931818
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+cbda931818
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+cbda931818
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+cbda931818
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.11+7931163218
	- fabric-renderer-api-v1@0.4.4+cbda931818
	- fabric-renderer-indigo@0.4.8+cbda931818
	- fabric-renderer-registries-v1@3.2.4+7931163218
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.14+4658223018
	- fabric-rendering-v0@1.1.5+7931163218
	- fabric-rendering-v1@1.9.0+7931163218
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+cbda931818
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.1+b06cb95b18
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.4.0+7931163218
	- fabricloader@0.11.7
	- jankson@3.0.1+j1.2.0
	- java@16
	- libgui@4.1.7+1.17.1
	- libninepatch@1.1.0
	- minecraft@1.17.1
	- modmenu@2.0.14
	- seedcrackerx@2.10.1
	- seedcrackerx-api@2.10.1
	- whereisit@1.14.3
[10:14:32] [main/WARN]: Mod `com_github_hube12_seed` (master-SNAPSHOT) does not respect SemVer - comparison support is limited.
[10:14:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Matthew/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[10:14:33] [main/INFO]: Compatibility level set to JAVA_16
[10:14:34] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/world/SodiumChunkManager (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/world/SodiumChunkManager)
[10:14:34] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/util/collections/FixedLongHashTable (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/util/collections/FixedLongHashTable)
[10:14:35] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[10:14:45] [main/WARN]: Method overwrite conflict for getInfiniburn in seedcracker.mixins.json:DimensionTypeMixin, previously written by me.zeroX150.atomic.mixin.game.DimensionTypeMixin. Skipping method.
[10:14:55] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:14:56] [Render thread/INFO]: Setting user: zBricky
[10:14:56] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zbd000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[10:14:56] [Render thread/INFO]: [Atomic client] Initializing
[10:14:57] [Render thread/INFO]: [Atomic client] Loading waypoints...
[10:14:57] [Render thread/INFO]: XRay mod has been initialized
[10:15:00] [Render thread/WARN]: WARNING! Mod jankson is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[10:15:00] [Render thread/WARN]: WARNING! Mod cloth-basic-math is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[10:15:00] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[10:15:01] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[10:15:06] [Render thread/INFO]: Narrator library for x64 successfully loaded
[10:15:07] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Transfer API (v1), Fabric Structure API (v1), Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Dimensions API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), Chest Tracker, Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Atomic client, Fabric Particles (v1), Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Mod Menu, Fabric Command API (v1), Jankson, Advanced XRay (Fabric), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Item API (v1), Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Where Is It, LibGui, Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Cloth Config v5, SeedCrackerX, Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), SeedCrackerX API, Fabric Biome API (v1), Fabric Registry Sync (v0), Fabric Commands (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Models (v0), Fabric Item Groups (v0), Fabric Object Builders (v0)), NoPumpkinBlur-rv1.2.zip
[10:15:08] [Render thread/INFO]: [STDOUT]: Baritone settings file not found, resetting.
[10:15:18] [Render thread/INFO]: OpenAL initialized.
[10:15:18] [Render thread/INFO]: Sound engine started
[10:15:19] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[10:15:19] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[10:15:19] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[10:15:19] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[10:15:19] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[10:15:19] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[10:15:19] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[10:15:22] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[10:15:22] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[10:15:22] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[10:16:13] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[10:16:13] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[10:16:13] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[10:16:13] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[10:16:13] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[10:16:13] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1))
[10:16:14] [Render thread/INFO]: Loaded 7 recipes
[10:16:14] [Render thread/INFO]: Loaded 1137 advancements
[10:16:14] [Render thread/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 3.251 ms
[10:16:16] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:16:16] [Server thread/INFO]: Starting integrated minecraft server version 1.17.1
[10:16:16] [Server thread/INFO]: Generating keypair
[10:16:17] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[10:16:18] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:18] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:18] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:18] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:19] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:28] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:29] [Render thread/INFO]: Preparing spawn area: 0%
[10:16:29] [Render thread/INFO]: Preparing spawn area: 10%
[10:16:30] [Render thread/INFO]: Preparing spawn area: 60%
[10:16:30] [Render thread/INFO]: Preparing spawn area: 78%
[10:16:32] [Render thread/INFO]: Preparing spawn area: 78%
[10:16:32] [Render thread/INFO]: Preparing spawn area: 78%
[10:16:32] [Render thread/INFO]: Preparing spawn area: 83%
[10:16:33] [Render thread/INFO]: Preparing spawn area: 85%
[10:16:34] [Render thread/INFO]: Preparing spawn area: 85%
[10:16:34] [Render thread/INFO]: Preparing spawn area: 85%
[10:16:34] [Render thread/INFO]: Preparing spawn area: 92%
[10:16:35] [Render thread/INFO]: Preparing spawn area: 93%
[10:16:35] [Render thread/INFO]: Preparing spawn area: 98%
[10:16:35] [Render thread/INFO]: Time elapsed: 18059 ms
[10:16:35] [Server thread/INFO]: Changing view distance to 8, from 10
[10:16:38] [Server thread/INFO]: zBricky[local:E:3a39b6f6] logged in with entity id 76 at (1650.9890799250231, 64.0, 124.4187706171515)
[10:16:38] [Server thread/INFO]: zBricky joined the game
[10:16:40] [Render thread/INFO]: [STDOUT]: Baritone world data dir: C:\Users\Matthew\AppData\Roaming\.minecraft\saves\New World (4)\.\baritone
[10:16:40] [Render thread/INFO]: [STDOUT]: Cached world directory: C:\Users\Matthew\AppData\Roaming\.minecraft\saves\New World (4)\.\baritone\cache
[10:16:40] [Render thread/INFO]: [STDOUT]: Would save waypoints to C:\Users\Matthew\AppData\Roaming\.minecraft\saves\New World (4)\.\baritone\waypoints
[10:16:41] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 4664ms or 93 ticks behind
[10:16:41] [Server thread/INFO]: Saving and pausing game...
[10:16:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[10:16:41] [Render thread/INFO]: Found data for singleplayer-New World (4)
[10:16:41] [Render thread/INFO]: Loaded singleplayer-New World (4)
[10:16:42] [Render thread/INFO]: [Atomic client] Enabling No Break Delay because config says so
[10:16:42] [Render thread/INFO]: [Atomic client] Enabling Waypoints because config says so
[10:16:42] [Render thread/INFO]: [Atomic client] Enabling Fullbright because config says so
[10:16:42] [Render thread/INFO]: [Atomic client] Enabling Tracers because config says so
[10:16:42] [Render thread/INFO]: [Atomic client] Enabling ESP because config says so
[10:16:43] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[10:16:43] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[10:16:44] [Render thread/INFO]: Loaded 7 advancements
[10:16:44] [Server thread/INFO]: Saving and pausing game...
[10:16:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[10:16:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[10:16:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[10:16:45] [pool-4-thread-1/INFO]: [STDOUT]: Loading region 3,0 from disk C:\Users\Matthew\AppData\Roaming\.minecraft\saves\New World (4)\.\baritone\cache
[10:16:46] [pool-4-thread-1/INFO]: [STDOUT]: Loaded region successfully in 1406ms
[10:16:55] [pool-4-thread-1/INFO]: [STDOUT]: Loading region 2,0 from disk C:\Users\Matthew\AppData\Roaming\.minecraft\saves\New World (4)\.\baritone\cache
[10:16:57] [pool-4-thread-1/INFO]: [STDOUT]: Loaded region successfully in 2001ms
[10:16:57] [pool-4-thread-1/INFO]: [STDOUT]: Loading region 3,-1 from disk C:\Users\Matthew\AppData\Roaming\.minecraft\saves\New World (4)\.\baritone\cache
[10:16:57] [pool-4-thread-1/INFO]: [STDOUT]: Loaded region successfully in 249ms
[10:16:59] [pool-4-thread-1/INFO]: [STDOUT]: Loading region 2,-1 from disk C:\Users\Matthew\AppData\Roaming\.minecraft\saves\New World (4)\.\baritone\cache
[10:17:00] [pool-4-thread-1/INFO]: [STDOUT]: Loaded region successfully in 343ms
[10:17:10] [pool-4-thread-2/INFO]: [STDOUT]: Saving region 2,-1 to disk C:\Users\Matthew\AppData\Roaming\.minecraft\saves\New World (4)\.\baritone\cache
[10:17:10] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saving region 3,0 to disk C:\Users\Matthew\AppData\Roaming\.minecraft\saves\New World (4)\.\baritone\cache
[10:17:10] [ForkJoinPool.commonPool-worker-5/INFO]: [STDOUT]: Saving region 3,-1 to disk C:\Users\Matthew\AppData\Roaming\.minecraft\saves\New World (4)\.\baritone\cache
[10:17:10] [ForkJoinPool.commonPool-worker-7/INFO]: [STDOUT]: Saving region 2,0 to disk C:\Users\Matthew\AppData\Roaming\.minecraft\saves\New World (4)\.\baritone\cache
[10:17:11] [pool-4-thread-2/INFO]: [STDOUT]: Saved region successfully
[10:17:11] [ForkJoinPool.commonPool-worker-5/INFO]: [STDOUT]: Saved region successfully
[10:17:11] [ForkJoinPool.commonPool-worker-3/INFO]: [STDOUT]: Saved region successfully
[10:17:11] [ForkJoinPool.commonPool-worker-7/INFO]: [STDOUT]: Saved region successfully
[10:17:11] [pool-4-thread-2/INFO]: [STDOUT]: World save took 851ms
[10:17:19] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2002ms or 40 ticks behind
[10:17:52] [Server thread/INFO]: Stopping server
[10:17:52] [Server thread/INFO]: Saving players
[10:17:52] [Server thread/INFO]: Saving worlds
[10:17:52] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[10:17:52] [Netty Local Client IO #0/INFO]: Saved data for singleplayer-New World (4)
[10:17:52] [Netty Server IO #1/INFO]: Saved data for singleplayer-New World (4)
[10:17:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[10:17:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[10:17:53] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World (4)): All chunks are saved
[10:17:53] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[10:17:53] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[10:17:53] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[10:17:54] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:883) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1112) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.7.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.7.jar:?]
Caused by: java.lang.IllegalAccessError: 'double pro.mikey.fabric.xray.screens.forge.RatioSliderWidget.getValue()'
	at net.minecraft.class_339.handler$zcf000$renderButton(class_339.java:574) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_339.method_25359(class_339.java) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_339.method_25394(class_339.java:67) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at net.minecraft.class_437.method_25394(class_437.java:107) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	at pro.mikey.fabric.xray.screens.forge.GuiBase.method_25394(GuiBase.java:117) ~[advanced-xray-fabric-1.17-0.6.0-build.8.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:874) ~[intermediary-fabric-loader-0.11.7-1.17.1.jar:?]
	... 10 more
[10:17:54] [Thread-72/INFO]: [Atomic client] Saving config
[10:17:54] [Thread-72/INFO]: [Atomic client] Saving 0 waypoints...
```

**Comment by MichaelHillcox** [comment]
This has almost definitely been fixed by now. Sorry for the very slow response
