### ISSUE TITLE
Game crashes when opening mod's GUI

### ISSUE THREAD

**Issue by LostyaWofer** [AdvancedXRay/XRay-Fabric#56]
**Describe the bug**
The game crashes, when trying to open mod's GUI.

**To Reproduce**
1. Open any world, or enter any server.
2. Tap open GUI key (default: G)

**Expected behavior**
Game should not crash.

**Minecraft Enviorment**
 - Minecraft Version: 1.19.3
 - XRay Mod Version: 1.3.0-build14
 - Fabric version: 0.14.12

**Additional context**
It didn't happen before. It started happening, after today my Minecraft disc got full, after wich I deleted some of replays to clean it up,
Rebooting PC and restarting launcher doesn't help.
Deleting and redownloading mod doesn't help.
Removing Sodium and mod that requires it Chunks fade in doesn't help.
After game crash, Minecraft Launcher shows this error:
```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "pro.mikey.fabric.xray.storage.BlockStore.get()" is null
```
Exit code: -1

Crash report:
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-01-06 17:28:37
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "pro.mikey.fabric.xray.storage.BlockStore.get()" is null
	at pro.mikey.fabric.xray.screens.forge.GuiSelectionScreen.<init>(GuiSelectionScreen.java:59)
	at pro.mikey.fabric.xray.XRay.clientTickEvent(XRay.java:76)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:62)
	at net.minecraft.class_310.handler$zlh000$onEndTick(class_310.java:5996)
	at net.minecraft.class_310.method_1574(class_310.java:1941)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pro.mikey.fabric.xray.screens.forge.GuiSelectionScreen.<init>(GuiSelectionScreen.java:59)
	at pro.mikey.fabric.xray.XRay.clientTickEvent(XRay.java:76)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:62)
	at net.minecraft.class_310.handler$zlh000$onEndTick(class_310.java:5996)

-- Affected level --
Details:
	All players: 1 total; [class_746['Lostya'/201, l='ClientLevel', x=225.51, y=67.00, z=-157.70]]
	Chunk stats: 1024, 204
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,69,-48), Section: (at 0,5,0 in -1,4,-3; chunk contains blocks -16,-64,-48 to -1,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 35649 game time, 35649 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, file/TBOI totem, file/Lostya's translate, file/Lostya's textures 1.19.3+, file/Lostya's music discs, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 904223912 bytes (862 MiB) / 1879048192 bytes (1792 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 530
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1912
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2111
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 14063.09
	Virtual memory used (MB): 11598.86
	Swap memory total (MB): 6000.00
	Swap memory used (MB): 770.56
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 1.19.3-1.3.0-build.14
		appleskin: AppleSkin 2.4.2+mc1.19.3
		architectury: Architectury 7.0.66
		betterf3: BetterF3 5.1.0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
		boostedbrightness: Boosted Brightness 2.1.2
		chunksfadein: Chunks Fade In 2.0.5-1.19.3
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		clientcommands: Client Commands 2.7.7
			clientarguments: clientarguments 1.4.2
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		craftpresence: CraftPresence 1.9.6
		dark-loading-screen: Dark Loading Screen 1.6.12
		dcch: DCCH 2.0+1.17
		fabric-api: Fabric API 0.70.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.0.1+f1e4495b85
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.29+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.10+99f9db8085
			fabric-command-api-v1: Fabric Command API (v1) 1.2.20+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.1.16+99f9db8085
			fabric-commands-v0: Fabric Commands (v0) 0.2.37+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.45+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.2+33a4e2d785
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.38+f1e4495b85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.40+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.6+99f9db8085
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.9+d3d735d085
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.29+aaaf9d3385
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.27+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.26+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.15+99f9db8085
			fabric-networking-v0: Fabric Networking (v0) 0.3.32+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.2.1+f1e4495b85
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.2+2608564685
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.1.1+afca2f3e85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.24+99f9db8085
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.29+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.32+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+6dc0edd785
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.1+280be3ab85
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.40+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.11+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.7+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.13+f1e4495b85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.2.0+1d37d50285
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.12
		ferritecore: FerriteCore 5.1.0
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		fpsreducer: FPS Reducer 1.19.3-2.2
		freecam: Freecam 1.1.8+1.19
		inventoryhud: Inventory HUD + 3.4.7
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.13.1
		malilib: MaLiLib 0.14.0
		minecraft: Minecraft 1.19.3
		modmenu: Mod Menu 5.0.2
		no_fog: No Fog 1.3.2+1.16.5-1.19.3
		nochatreports: No Chat Reports 1.19.3-v1.19.0
		phosphor: Phosphor 0.8.1
		presencefootsteps: Presence Footsteps 1.7.1
			kirin: Kirin UI 1.13.2
		replaymod: Replay Mod 1.19.3-2.6.10
		roughlyenoughitems: Roughly Enough Items 10.0.581
			error_notifier: Error Notifier 1.0.9
		shulkerboxtooltip: Shulker Box Tooltip 3.2.4+1.19.3
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		smoothswapping: Smooth Swapping 0.6.1
		sodium: Sodium 0.4.8+build.22
		timestamp_chat: Timestamp Chat 2.2.4
		viafabric: ViaFabric 0.4.9+22-main
			org_yaml_snakeyaml: snakeyaml 1.33
			viafabric-mc119: ViaFabric for 1.19 0.4.9+22-main
			viaversion: ViaVersion 4.5.0
		xaerominimap: Xaero's Minimap 22.17.0
	Launched Version: fabric-loader-0.14.12-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) HD Graphics 530 GL version 3.2.0 - Build 31.0.101.2111, Intel
	Window size: 1440x900
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/TBOI totem (incompatible), file/Lostya's translate (incompatible), file/Lostya's textures 1.19.3+ (incompatible), file/Lostya's music discs (incompatible)
	Current Language: Русский (Россия)
	CPU: 4x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Lostya'/201, l='ServerLevel[тест проверка lan/wan]', x=225.51, y=67.00, z=-157.70]]
	Data Packs: vanilla, fabric, file/clear_ground (incompatible), file/invulnerability (incompatible), file/restart (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
```

**Comment by UncleEnk** [comment]
i am also having this issue, i when(/if) i figure the problem i will say here

**Comment by voytax** [comment]
Got the same error, caused by java.lang.NoClassDefFoundError: net/minecraft/class_7871

**Comment by MichaelHillcox** [comment]
Update
